account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('terms/', views.terms, name='terms'),
    path('login/', views.login_view, name='login'), 
    path('register/', views.register, name='register'),
    path('adminpage/',views.admin, name='adminpage'),
    path('report/<str:report_type>/',views.report, name='report'),
    path('tenant/',views.tenant, name='tenant'),
    path('<pk>/tenant_profile/',views.tenant_profile, name='tenant_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('landlord/',views.landlord, name='landlord'),
    path('logout/', views.logout_view, name='logout')
]

listing/urls.py
from django.urls import path
from . import views
    
app_name = 'listing'

urlpatterns = [
    path('', views.add_listing, name='add_listing'),
    path('<pk>/', views.view_listing, name='view_listing'),
    path('<pk>/edit/', views.edit_listing, name='edit_listing'),
    path('<pk>/listing_bookings/', views.listing_bookings, name='listing_bookings'),
    path('<pk>/bookings_chart/', views.bookings_chart, name='bookings_chart'),
    path('<pk>/listing_bookings/pdf/', views.listing_bookings_pdf, name='listing_bookings_pdf'),
    path('<pk>/whatsapp/', views.whatsapp_chat, name='whatsapp_chat'),#url for whatsapp chat page
]

my_rental2/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('listings/', include('listing.urls')),
    path('payment/', include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('<pk>/', views.book_listing, name='book_listing'),
    path('<pk>/booking_report/', views.booking_report, name='booking_report'),
    path('<pk>/mpesa_callback/', views.mpesa_callback, name='mpesa_callback'),
    path('<pk>/pay_rent/', views.pay_rent, name='pay_rent'),
    path('<pk>/mpesa_rent_callback/', views.mpesa_rent_callback, name='mpesa_rent_callback'),
    path('<pk>/<listing_pk>/tenant_rent_history/',views.tenant_rent_history, name='tenant_rent_history'),
    path('<pk>/landlord_rent_history/',views.landlord_rent_history, name='landlord_rent_history'),
    path('<pk>/download_rent_history/', views.download_rent_history, name='download_rent_history'),
]

listing/models.py
from django.db import models
from account.models import User

# Create your models here.
class ListingType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class ListingItem(models.Model):
    landlord = models.ForeignKey(User, on_delete=models.CASCADE)
    listing_type = models.ForeignKey(ListingType, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    location = models.CharField(max_length=255)
    description = models.TextField()
    vacancies = models.IntegerField()
    is_available = models.BooleanField(default=True)
    image = models.ImageField()
    booking_fee = models.IntegerField()
    features = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    booked_by = models.ManyToManyField(User, related_name='booked_listings', blank=True)
    rented_by = models.ManyToManyField(User, related_name='rented_listings', blank=True)

    def __str__(self):
        return self.name
    
    def display_date(self):
        if self.created_at == self.updated_at:
            return self.created_at
        else:
            return self.updated_at
    
    @property
    def landlord_username(self):
        return self.landlord.username
    
    
    
    
    

listing/forms.py
from django.forms import ModelForm
from .models import ListingItem

class ListingItemForm(ModelForm):
    class Meta:
        model = ListingItem
        fields = ['listing_type','name', 'price', 'location', 'description','vacancies', 'is_available','image','booking_fee','features']

    #for styling the form
    def __init__(self, *args, **kwargs):
        super(ListingItemForm, self).__init__(*args, **kwargs)
        self.fields['listing_type'].widget.attrs.update({'class': 'myfieldclass'})
        self.fields['price'].widget.attrs.update({'class': 'myfieldclass'})
        self.fields['description'].widget.attrs.update({'class': 'myfieldclass-description'})
        self.fields['vacancies'].widget.attrs.update({'class': 'myfieldclass'})
        self.fields['booking_fee'].widget.attrs.update({'class': 'myfieldclass'})
        self.fields['features'].widget.attrs.update({'class': 'myfieldclass-features'})

listing/views.py
from django.shortcuts import get_object_or_404, render, redirect
import urllib
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta

from listing.forms import ListingItemForm
from listing.models import ListingItem
from payment.models import Booking, Renting

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from django.http import HttpResponse
from matplotlib.backends.backend_agg import FigureCanvasAgg
import calendar

import os
from django.conf import settings
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.templatetags.static import static
from django.contrib.staticfiles import finders


@login_required
def add_listing(request):
    if not request.user.is_landlord:
        return redirect('account:tenant' if request.user.is_tenant else 'account:adminpage' if request.user.is_admin else 'account:login')
    
    form = ListingItemForm()
    if request.method == 'POST':
        form = ListingItemForm(request.POST, request.FILES)
        if form.is_valid():
            #set the landlord field to the current user
            form.instance.landlord = request.user
            form.save()
            return redirect('/landlord/')
    context = {
        'form': form
    }
    return render(request, 'listing/add_listing.html', context)
    

@login_required
def view_listing(request, pk):
    listing = ListingItem.objects.get(id=pk)
    if request.user.is_authenticated:
        rent_month = None
        renting = Renting.objects.filter(listing=listing, renting_tenant=request.user.username).first()
        if renting:
            rent_month = renting.transaction_date.strftime('%B')

        context = {
            'listing': listing,
            'rent_month': rent_month,
        }
        if request.user == listing.landlord:
            bookings = Booking.objects.filter(listing=listing)[:2]
            context['bookings'] = bookings
        return render(request,'listing/view_listing.html', context)
    else:
        return redirect('account:login')

@login_required
def edit_listing(request, pk):
    if not request.user.is_landlord:
        return redirect('account:tenant' if request.user.is_tenant else 'account:adminpage' if request.user.is_admin else 'account:login')
    
    listing = ListingItem.objects.get(id=pk)
    form = ListingItemForm(instance=listing)

    if request.method == 'POST':
        form = ListingItemForm(request.POST, instance=listing, files=request.FILES)
        if form.is_valid():
            #set the landlord field to the current user
            form.instance.landlord = request.user
            form.save()
            return redirect('listing:view_listing', pk=listing.id)
    context = {
        'form': form,
        'listing': listing
    }
    return render(request, 'listing/edit_listing.html', context)

@login_required
def listing_bookings(request, pk):
    if not request.user.is_landlord:
        return redirect('account:tenant' if request.user.is_tenant else 'account:adminpage' if request.user.is_admin else 'account:login')
    listing = ListingItem.objects.get(id=pk)

    if request.user == listing.landlord:
        bookings = Booking.objects.filter(listing=listing)
        listing_name = listing.name

        #filtering listings based on transaction date
        if 'transaction_date' in request.GET:
            q = request.GET['transaction_date']
            if q == 'today':
                bookings = bookings.filter(transaction_date__date=datetime.today())
            elif q == 'this_week':
                start_date = datetime.today() - timedelta(days=datetime.today().weekday())
                end_date = start_date + timedelta(days=6)
                bookings = bookings.filter(transaction_date__date__range=[start_date, end_date])
            elif q == 'this_month':
                start_date = datetime.today().replace(day=1)
                end_date = (start_date + timedelta(days=31)).replace(day=1) - timedelta(days=1)
                bookings = bookings.filter(transaction_date__date__range=[start_date, end_date])

        #calculate summary statistics
        total_bookings = bookings.count()
        total_revenue = sum(booking.amount_paid for booking in bookings)
        average_revenue = total_revenue / total_bookings if total_bookings > 0 else 0
        context = {
            'bookings': bookings,
            'total_bookings': total_bookings,
            'total_revenue': total_revenue,
            'average_revenue': average_revenue,
            'listing_name': listing_name,
            'listing': listing,
        }
    return render(request, 'listing/listing_bookings.html', context)

@login_required
def bookings_chart(request, pk):
    listing = ListingItem.objects.get(id=pk)
    bookings = Booking.objects.filter(listing=listing)
    data = {}
    for booking in bookings:
        month = booking.transaction_date.month
        if month not in data:
            data[month] = 0
        data[month] += 1

    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    ax.bar(data.keys(), data.values())
    ax.set_xlabel('Month')
    ax.set_ylabel('Number of Bookings')
    ax.set_title(f'Number of Bookings for listing {listing.name} (2023)')
    
    #set y-axis tick labels to integer values
    ax.set_yticks(range(0, int(max(data.values()) + 1)))
    
    #set x-axis tick labels to month names
    month_names = [calendar.month_abbr[i] for i in range(1, 13)]
    ax.set_xticks(range(1, 13))
    ax.set_xticklabels(month_names)

    canvas = FigureCanvasAgg(fig)
    response = HttpResponse(content_type='image/png')
    canvas.print_png(response)
    return response

@login_required
def listing_bookings_pdf(request, pk):
    listing = ListingItem.objects.get(id=pk)
    bookings = Booking.objects.filter(listing=listing)
    listing_name = listing.name

    # set default value for title
    title = 'All Time'

    #filtering listings based on transaction date
    transaction_date = request.GET.get('transaction_date')
    if transaction_date:
        if transaction_date == 'today':
            bookings = bookings.filter(transaction_date__date=datetime.today())
            title = 'Today'
        elif transaction_date == 'this_week':
            start_date = datetime.today() - timedelta(days=datetime.today().weekday())
            end_date = start_date + timedelta(days=6)
            bookings = bookings.filter(transaction_date__date__range=[start_date, end_date])
            title = 'This Week'
        elif transaction_date == 'this_month':
            start_date = datetime.today().replace(day=1)
            end_date = (start_date + timedelta(days=31)).replace(day=1) - timedelta(days=1)
            bookings = bookings.filter(transaction_date__date__range=[start_date, end_date])
            title = 'This Month'

    #calculate summary statistics
    total_bookings = bookings.count()
    total_revenue = sum(booking.amount_paid for booking in bookings)
    average_revenue = total_revenue / total_bookings if total_bookings > 0 else 0
    context = {
        'bookings': bookings,
        'total_bookings': total_bookings,
        'total_revenue': total_revenue,
        'average_revenue': average_revenue,
        'listing_name': listing_name,
        'title': title,
    }

    template = get_template('listing/listing_bookings_pdf.html')
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{listing_name} Bookings.pdf"'

    pisa_status = pisa.CreatePDF(
        html, dest=response, link_callback=fetch_resources)
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

def fetch_resources(uri, rel):
    if uri.startswith(settings.MEDIA_URL):
        path = os.path.join(settings.MEDIA_ROOT, uri.replace(settings.MEDIA_URL, ''))
    elif uri.startswith(settings.STATIC_URL):
        path = finders.find(uri.replace(settings.STATIC_URL, ''))
    else:
        path = static(uri)
    return path


#redirecting the user to the whatsapp chat page
@login_required
def whatsapp_chat(request, pk):
    listing = get_object_or_404(ListingItem, id=pk)
    landlord_phone_number = '254' + listing.landlord.phone_number[1:]
    tenant_phone_number = request.user.phone_number
    base_url = 'https://wa.me/'
    url = f'{base_url}{landlord_phone_number}?text={urllib.parse.quote(f"Hello, I am interested in your {listing.name} listing.")}'
    return redirect(url)

listing/templates/listing/add_listing.html
{% extends "account/index.html" %}

{% block title %}Add Listing{% endblock %}

{% block content %}
<div class="bg-gradient-to-b from-neutral-300 p-8">
  <div class="bg-gray-100 py-8 px-4 sm:px-8 md:px-12 mx-auto rounded sm:w-2/3">
    <h2 class="text-2xl text-blue-500 font-bold mb-4">Add a Listing</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="flex flex-col space-y-4">
        {{ form.as_p }}
        <div class="block sm:flex">
          <button class="px-4 py-2 font-bold bg-blue-500 text-white rounded hover:bg-blue-700 transition-colors duration-300 mb-2 sm:mb-0 sm:mr-5">Post Listing</button>
          
          <a href="{% url 'account:landlord' %}" class="px-4 py-2 font-bold bg-zinc-700 text-white rounded transition-colors duration-300 mb-2 sm:mb-0">Cancel</a>
        </div>
      </div>
    </form> 
  </div>
</div>
{% endblock %}

listing/templates/listing/edit_listing.html
{% extends "account/index.html" %}

{% block title %}Edit listing{% endblock %} 

{% block content %}
<div class="bg-gradient-to-b from-neutral-300 p-8">
    <div class="bg-gray-100 py-8 px-4 sm:px-8 md:px-12 mx-auto rounded sm:w-2/3">
        <p class="font-bold mb-4 text-blue-500 text-2xl">Edit your listing</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="flex flex-col space-y-4">
                {{ form.as_p }}
                <div class="block sm:flex">
                    <button class="px-4 py-2 font-bold bg-blue-500 text-white rounded hover:bg-blue-700 transition-colors duration-300 mb-2 sm:mb-0 sm:mr-5">Edit listing</button>

                    <a href="{% url 'account:landlord' %}" class="px-4 py-2 font-bold bg-zinc-700 text-white rounded transition-colors duration-300 mb-2 sm:mb-0">Cancel</a>
                </div>
            </div>
        </form>
        <!-- <p><a href="{% url 'listing:view_listing' pk=listing.pk %}" class="text-blue-500 hover:text-blue-700">Back</a></p> -->
    </div>
</div>

    
{% endblock %}

listing/templates/listing/listing_bookings.html
{% extends "account/index.html" %}
{% load humanize %}
{% block title %}Listing bookings{% endblock %} 

{% block content %}
<div class="flex flex-col sm:flex-row m-4 space-y-4 sm:space-y-0 sm:space-x-4 mt-8">
    <div class="flex-1 p-2">
        <p class="mb-5 font-semibold text-xl ">More details on <span class="text-blue-500 font-bold">{{ listing_name }}</span> bookings: </p>
        <div class="space-y-6">
            <!--dropdown menu for transaction date to search form-->
            <form class="flex flex-col sm:flex-row items-center space-y-4 sm:space-y-0 sm:space-x-1">
                <select class="bg-gray-200 border border-gray-300 rounded p-2 w-full sm:w-56" name="transaction_date">
                    <option value="">Filter by transaction date</option>
                    <option value="today">Today</option>
                    <option value="this_week">This week</option>
                    <option value="this_month">This month</option>
                    <option value="all_time">All time</option>
                </select>
                <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded w-full sm:w-auto" type="submit">Search</button>
            </form>
            <!--end of dropdown menu-->
            <!--booking table to show transactions based on filtered dates-->
            <div class="overflow-x-auto">
                <table class="w-full sm:w-max">
                    <thead>
                        <tr>
                            <th class="border px-2 py-1"></th>
                            <th class="border px-2 py-1 font-semibold">Tenant name</th>
                            <th class="border px-2 py-1 font-semibold">Tenant no</th>
                            <th class="border px-2 py-1 font-semibold">Transaction date</th>
                            <th class="border px-2 py-1 font-semibold">Amount paid (Ksh)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for booking in bookings %}
                        <tr>
                            <td class="border px-2 py-1">{{ forloop.counter }}</td>
                            <td class="border px-2 py-1">{{ booking.booking_tenant }}</td>
                            <td class="border px-2 py-1">{{ booking.tenant_phone_number }}</td>
                            <td class="border px-2 py-1">{{ booking.transaction_date }}</td>
                            <td class="border px-2 py-1">{{ booking.amount_paid|intcomma }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!--end of table-->
            <!--summary of table-->
            <div>
                <p class="font-bold underline">Summary:</p>
                <p><span class="font-semibold">Total bookings:</span> {{ total_bookings }}</p>
                <p><span class="font-semibold">Total revenue: </span>Ksh {{ total_revenue|intcomma }}</p>
                <p class="mb-6"><span class="font-semibold">Average revenue per booking: </span>Ksh {{ average_revenue|intcomma }}</p>
            </div>
            <!--end of summary-->
            <a href="{% url 'listing:listing_bookings_pdf' pk=listing.pk %}{% if request.GET.transaction_date %}?transaction_date={{ request.GET.transaction_date }}{% endif %}" class="bg-blue-500 text-white p-2 rounded"><i class="fas fa-download"></i> Download the summary</a>

        </div>
    </div>

    <div class="flex-1 p-2">
        <img src="{% url 'listing:bookings_chart' pk=listing.pk %}" alt="Bookings Chart" class="w-auto sm:w-full">
    </div>
</div>
{% endblock %}

listing/templates/listing/view_listing.html
{% extends "account/index.html" %}
{% load humanize %}

{% block title %}View a listing{% endblock %} 

{% block content %}
<style>
.listing-image {
  width: 100%;
  height: 90%;
  object-fit: cover;
}
</style>
<div class="bg-gray-200 p-4 sm:p-8">
    <div class="flex flex-col sm:flex-row bg-gray-100">
        <div class="w-full sm:w-1/2 px-4 bg-white rounded pt-6">
            <img src="{{ listing.image.url }}" alt="img" class="listing-image">
        </div>
        <div class="w-full sm:w-1/2 px-4 py-2 bg-gray-100 rounded pt-6 ml-4 space-y-4">
            <div class="flex items-center justify-between">
                <div class="flex flex-col sm:flex-row items-start"> 
                    <p class="text-2xl font-bold text-blue-500 mb-2 sm:mb-0"> 
                      {{ listing.name }}
                    </p>
                    <p class="sm:ml-24 mt-1"> 
                      <i class="fa-solid fa-calendar-days mr-1"></i>Date posted: {{ listing.display_date }}
                    </p>
                  </div>
            </div>
            <p>Listing type: {{ listing.listing_type }}</p>
            <p class="text-lg"><i class="fas fa-map-marker-alt text-gray-600 mr-2"></i>{{ listing.location }}</p>
            <p class="mb-2 text-base"><i class="fas fa-money-bill-wave text-gray-600 mr-1"></i>Ksh {{ listing.price|intcomma }} per month <span class="italic">(after moving in)</span></p>
            <p class="text-gray-500 text-lg mb-2">{{ listing.description }}</p>
            <p class="mb-2 text-base"><span class="font-semibold">Extra charges:</span> Ksh {{ listing.booking_fee|intcomma }} <span class="italic">(to be paid when booking)</span></p>
            <p class="mb-6 text-base"><span class="font-semibold">Features: </span>{{ listing.features }}</p>

            {% if user.is_landlord %}
                <!-- <p><a href="{% url 'account:landlord' %}" class="text-blue-700 hover:text-blue-900">Back</a></p> -->
                {% if listing.vacancies > 0 %}
                    <p class="text-base"><span class="font-semibold">Vacancies: </span>{{ listing.vacancies }}</p>
                {% else %}
                    <p class="text-red-500 font-bold">No more vacancies </p>
                {% endif %}

            {% else %}
                {% if request.user in listing.booked_by.all %}
                <div id="popup-message" style="display: none;"></div>
                <form id="pay-rent-form" action="{% url 'payment:pay_rent' pk=listing.pk %}" target="_blank">
                    {% csrf_token %}
                    <button id="pay-rent-button" type="submit" class="bg-green-500 hover:bg--700 text-white font-bold py-2 px-4 my-4 rounded ease-in-out hover:scale-95 flex items-center space-x-2">
                        <i class="fas fa-coins"></i>
                        <span class="ml-2">Pay Rent</span>
                    </button>
                </form>
                {% if rent_month %}
                    <p class="text-green-600 font-bold">You have paid rent for {{ rent_month }}.</p>
                    <a href="{% url 'payment:tenant_rent_history' pk=user.pk listing_pk=listing.pk %}" class="text-sm text-blue-500 hover:text-blue-600">See rent payment history here</a>
                {% endif %}
                {% else %}
                    <p class="text-base"><span class="font-semibold">Vacancies: </span>{{ listing.vacancies }}</p>
                    <div id="popup-message" style="display: none;"></div>
                    <form id="booking-form" action="{% url 'payment:book_listing' pk=listing.pk %}">
                        {% csrf_token %}
                        <button id="book-now-button" type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 my-4 rounded ease-in-out hover:scale-95 flex items-center space-x-2">
                            <i class="fa-regular fa-calendar-plus"></i>
                            <span class="ml-2">Book Now</span>
                        </button>
                    </form>
                {% endif %}
            {% endif %}


            <!--Only the landlord who created the listing can edit--> 
            {% if user.is_landlord %}
            <div class="flex items-center justify-between">  
                <a href="{% url 'listing:edit_listing' pk=listing.pk %}" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4  rounded mr-4">Edit</a> 
                <a href="{% url 'payment:booking_report' pk=listing.pk %}" target="_blank" class="font-bold bg-blue-500 hover:bg-blue-600 text-white py-2 px-3 rounded">Report on listing</a>
            </div>
            <div>
                <a href="{% url 'payment:landlord_rent_history' pk=listing.pk%}" class="text-sm text-blue-500 hover:text-blue-600">See rent payment history here</a>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="p-6 mt-4 bg-white">
        {% if user.is_landlord %}
        <div class="flex flex-col sm:flex-row">
            <div class="flex-1 mb-7">
                <p class="font-bold mb-2 underline">Your info:</p>
                <p><span class="font-semibold">Username</span> : {{ listing.landlord }}</p>
                <p><span class="font-semibold">Email</span> : {{ listing.landlord.email }}</p>
                <p class="mb-2"><span class="font-semibold">Phone no</span>: {{ listing.landlord.phone_number }}</p>
                <a href="{% url 'account:update_profile' %}" class="text-blue-500"><i class="fa-solid fa-pen-to-square mr-1"></i>Edit your details</a>
            </div>
            <div class="flex-1 overflow-x-auto">
                <h2 class="text-center mb-1 font-bold">Tenants who have booked this listing</h2>
                <div class="flex flex-col">
                    <table>
                        <thead>
                            <tr>
                                <th class="border px-2 py-1"></th>
                                <th class="border px-2 py-1 font-semibold">Tenant name</th>
                                <th class="border px-2 py-1 font-semibold">Tenant no</th>
                                <th class="border px-2 py-1 font-semibold">Transaction date</th>
                                <th class="border px-2 py-1 font-semibold">Amount paid (Ksh)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for booking in bookings %}
                            <tr>
                                <td class="border px-2 py-1">{{ forloop.counter }}</td>
                                <td class="border px-2 py-1">{{ booking.booking_tenant }}</td>
                                <td class="border px-2 py-1">{{ booking.tenant_phone_number }}</td>
                                <td class="border px-2 py-1">{{ booking.transaction_date }}</td>
                                <td class="border px-2 py-1">{{ booking.amount_paid|intcomma }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="flex justify-end mt-2">
                        <a href="{% url 'listing:listing_bookings' pk=listing.pk %}" class="text-blue-500 hover:text-blue-600">See more...</a>
                    </div>
                </div> 
            </div>
        </div>

        {% else %}
        <div class="grid">
            <h2 class="font-bold text-xl">Contact agent</h2>
            <p>Feel free to reach out to the agent for any inquiries or comments: </p>

            <!--to email page-->
            <a href="https://mail.google.com/mail/?view=cm&to={{ listing.landlord.email }}&su=Regarding%20{{ listing.name }}" target="_blank" class="bg-red-500 hover:bg-white text-white hover:text-red-500 border border-red-500 py-2 px-4 rounded-lg text-center transition duration-500 ease-in-out mt-4">
                <span class="flex items-center justify-center space-x-2">
                    <i class="fas fa-envelope"></i>
                    <span>Send Mail</span>
                </span>
            </a>

            <!--to whatsapp chat page-->
            <a href="{% url 'listing:whatsapp_chat' pk=listing.pk %}" target="_blank" class="bg-green-500 hover:bg-white text-white hover:text-green-500 border border-green-500 py-2 px-4 rounded-lg text-center transition duration-500 ease-in-out mt-4">
                <span class="flex items-center justify-center space-x-2">
                    <i class="fab fa-whatsapp"></i>
                    <span>Chat on Whatsapp</span>
                </span>
            </a>
        </div>
        {% endif %}

    </div>
</div>
<script>
    // get the form, button, and popup message elements
    const bookingForm = document.querySelector('#booking-form');
    const bookNowButton = document.querySelector('#book-now-button');
    const payRentForm = document.querySelector('#pay-rent-form');
    const payRentButton = document.querySelector('#pay-rent-button');
    const popupMessage = document.querySelector('#popup-message');

    // check if the bookingForm element exists
    if (bookingForm) {
        // add an event listener to the bookingForm's submit event
        bookingForm.addEventListener('submit', function(event) {
            // prevent the default form submission behavior
            event.preventDefault();
            // disable the button to prevent multiple submissions
            bookNowButton.disabled = true;
            // get the form data
            const formData = new FormData(bookingForm);
            // send the form data using AJAX
            fetch(bookingForm.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': formData.get('csrfmiddlewaretoken')
                }
            })
            .then(response => response.text())
            .then(data => {
                // display the pop-up message
                popupMessage.textContent = 'Please check your phone and enter your M-PESA pin to book. Refresh the page after successful payment.';
                popupMessage.style.display = 'block';
                // apply inline styles to the popupMessage element
                popupMessage.style.color = 'green';
                popupMessage.style.fontWeight = 'bold';
                // re-enable the button
                bookNowButton.disabled = false;
            })
            .catch(error => {
                console.error('An error occurred:', error);
                // re-enable the button
                bookNowButton.disabled = false;
            });
        });
    }

    // check if the payRentForm element exists
    if (payRentForm) {
        // add an event listener to the payRentForm's submit event
        payRentForm.addEventListener('submit', function(event) {
            // prevent the default form submission behavior
            event.preventDefault();
            // disable the button to prevent multiple submissions
            payRentButton.disabled = true;
            // get the form data
            const formData = new FormData(payRentForm);
            // send the form data using AJAX
            fetch(payRentForm.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': formData.get('csrfmiddlewaretoken')
                }
            })
            .then(response => response.text())
            .then(data => {
                // display the pop-up message
                popupMessage.textContent = 'Please check your phone and enter your M-PESA pin to pay rent. Refresh the page after successful payment.';
                popupMessage.style.display = 'block';
                // apply inline styles to the popupMessage element
                popupMessage.style.color = 'green';
                popupMessage.style.fontWeight = 'bold';
                // re-enable the button
                payRentButton.disabled = false;
            })
            .catch(error => {
                console.error('An error occurred:', error);
                // re-enable the button
                payRentButton.disabled = false;
            });
        });
    }
</script>
{% endblock %}