account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('terms/', views.terms, name='terms'),
    path('login/', views.login_view, name='login'), 
    path('register/', views.register, name='register'),
    path('adminpage/',views.admin, name='adminpage'),
    path('report/<str:report_type>/',views.report, name='report'),
    path('tenant/',views.tenant, name='tenant'),
    path('<pk>/tenant_profile/',views.tenant_profile, name='tenant_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('landlord/',views.landlord, name='landlord'),
    path('logout/', views.logout_view, name='logout')
]

listing/urls.py
from django.urls import path
from . import views
    
app_name = 'listing'

urlpatterns = [
    path('', views.add_listing, name='add_listing'),
    path('<pk>/', views.view_listing, name='view_listing'),
    path('<pk>/edit/', views.edit_listing, name='edit_listing'),
    path('<pk>/listing_bookings/', views.listing_bookings, name='listing_bookings'),
    path('<pk>/bookings_chart/', views.bookings_chart, name='bookings_chart'),
    path('<pk>/listing_bookings/pdf/', views.listing_bookings_pdf, name='listing_bookings_pdf'),
    path('<pk>/whatsapp/', views.whatsapp_chat, name='whatsapp_chat'),#url for whatsapp chat page
]

my_rental2/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('listings/', include('listing.urls')),
    path('payment/', include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('<pk>/', views.book_listing, name='book_listing'),
    path('<pk>/booking_report/', views.booking_report, name='booking_report'),
    path('<pk>/mpesa_callback/', views.mpesa_callback, name='mpesa_callback'),
    path('<pk>/pay_rent/', views.pay_rent, name='pay_rent'),
    path('<pk>/mpesa_rent_callback/', views.mpesa_rent_callback, name='mpesa_rent_callback'),
    path('<pk>/<listing_pk>/tenant_rent_history/',views.tenant_rent_history, name='tenant_rent_history'),
    path('<pk>/landlord_rent_history/',views.landlord_rent_history, name='landlord_rent_history'),
    path('<pk>/download_rent_history/', views.download_rent_history, name='download_rent_history'),
]

payment/models.py
from django.db import models
from account.models import User
from listing.models import ListingItem

class Booking(models.Model):
    listing = models.ForeignKey(ListingItem, on_delete=models.CASCADE)
    booking_tenant = models.CharField(max_length=255)
    transaction_code = models.CharField(max_length=255)
    tenant_phone_number = models.CharField(max_length=255)
    transaction_date = models.DateTimeField()
    amount_paid = models.IntegerField()

    def __str__(self):
        return f"{self.listing.name} - {self.booking_tenant}" 
    

class Renting(models.Model):
    listing = models.ForeignKey(ListingItem, on_delete=models.CASCADE)
    renting_tenant = models.CharField(max_length=255)
    transaction_code = models.CharField(max_length=255)
    tenant_phone_number = models.CharField(max_length=255)
    transaction_date = models.DateTimeField()
    amount_paid = models.IntegerField()

    def __str__(self):
        return f"{self.listing.name} - {self.renting_tenant}"

payment/views.py
from datetime import datetime
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from account.models import User
from listing.models import ListingItem
from .models import Booking, Renting
from django.http import HttpResponse, HttpResponseForbidden
from django_daraja.mpesa.core import MpesaClient

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Avg

from django.http import FileResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
import io
from reportlab.lib.utils import ImageReader
from django.template.loader import render_to_string
from django.utils.text import slugify
from xhtml2pdf import pisa
import os
from django.conf import settings
from django.contrib.staticfiles import finders
from django.templatetags.static import static
from django.template.loader import get_template

@csrf_exempt
@login_required
def book_listing(request,pk):
    print("IS THE USER AUTHENTICATED?",request.user.is_authenticated)
    print(request.user.phone_number)
    if request.user.is_tenant:
        print("REQUEST.USER.IS_TENANT",request.user.is_tenant)
        if not request.user.is_tenant:
            return HttpResponseForbidden()
        listing = get_object_or_404(ListingItem, pk=pk)

        cl = MpesaClient()

        phone_number = request.user.phone_number
        amount = listing.booking_fee
        account_reference = 'HouseQuest'
        transaction_desc = 'Payment of booking fee'
        callback_url = f'https://7964-105-166-142-54.ngrok-free.app/payment/{pk}/mpesa_callback/'
        response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)      
        print(response)
    return HttpResponse(response)

@csrf_exempt
def mpesa_callback(request, pk):
    listing = get_object_or_404(ListingItem, pk=pk)

    result = request.body
    cl = MpesaClient()
    data = cl.parse_stk_result(result)

    result_code = data['ResultCode']
    result_desc = data['ResultDesc']
    print(data)

    if result_code == 0:
        print("Transaction was successful")

        amount_paid = data.get('Amount')
        print(f"Booking fee paid: Ksh{amount_paid}")

        transaction_date_str = str(data.get('TransactionDate'))
        transaction_date = datetime.strptime(transaction_date_str, "%Y%m%d%H%M%S")
        transaction_date = timezone.make_aware(transaction_date) #make the datetime object timezone-aware
        iso_date = transaction_date.isoformat()
        print(f"Transaction date string: {transaction_date}")


        tenant_phone_number =  data.get('PhoneNumber')
        print(f"Tenant's Phone number: {tenant_phone_number}")

        transaction_code = data.get('MpesaReceiptNumber')
        print(f"Transaction code: {transaction_code}")

        listing_name = listing.name
        print("Listing booked: ",listing_name)
        
        if tenant_phone_number:
            tenant_phone_number = str(tenant_phone_number)
            if tenant_phone_number.startswith('254'):
                tenant_phone_number = '0' + tenant_phone_number[3:]

        user = User.objects.filter(phone_number=tenant_phone_number).first()
        if user:
            username = user.get_username()
            print(f"Tenant who booked: {username}")
            listing.booked_by.add(user)
            listing.vacancies -= 1
            if listing.vacancies == 0:
                listing.is_available = False
            listing.save()
        else:
            print("User not found")

        #creating Booking object
        booking = Booking(
            listing = listing,
            booking_tenant = username,
            transaction_code = transaction_code,
            tenant_phone_number = tenant_phone_number,
            transaction_date = iso_date,
            amount_paid = amount_paid,
        )
        booking.save()
        print(f"Booking created: {booking}")

    else:
        print("Transaction was UNsuccessful")

    return HttpResponse('Callback handled')

@login_required
def booking_report(request, pk):
    if not request.user.is_landlord:
        return redirect('account:tenant' if request.user.is_tenant else 'account:adminpage' if request.user.is_admin else 'account:login')
    listing = ListingItem.objects.get(id=pk)
    bookings = Booking.objects.filter(listing=listing) #get all bookings for the listing

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    top_margin = 0.75 * inch
    bottom_margin = 0.75 * inch

    #add the logo to each page
    logo_path = "account/static/images/logo.PNG" 
    logo_image = ImageReader(logo_path)
    logo_width, logo_height = logo_image.getSize()
    logo_scale = 0.5 #scale down the logo image
    logo_width *= logo_scale
    logo_height *= logo_scale
    logo_x = (letter[0] - logo_width) / 2
    logo_y = letter[1] - top_margin - (logo_height / 2)
    c.drawImage(logo_image, logo_x, logo_y, width=logo_width, height=logo_height)

    #add the title below the logo
    c.setFont("Helvetica-Bold", 18)
    title_x = inch * 0.5
    title_y = letter[1] - top_margin - inch * 1.5 #adjust the vertical position of the title by increasing the distance from the top margin
    total_bookings = bookings.count()
    title = f"Tenants who have booked {listing.name.upper()} listing"
    c.drawString(title_x, title_y, title)

    # Add the subtitle below the title
    c.setFont("Helvetica", 14)
    subtitle_x = inch * 0.5
    subtitle_y = title_y - 0.2 * inch # adjust the vertical position of the subtitle by increasing the distance from the title
    subtitle = f"Total bookings: {total_bookings}"
    c.drawString(subtitle_x, subtitle_y, subtitle)

    text_y = title_y - 0.5 * inch
    lines = []

    counter = 1 #initialize a counter to number the bookings

    for booking in bookings:
        lines.append(f"{counter}. Tenant: {booking.booking_tenant}")
        lines.append(f"    Phone number: {booking.tenant_phone_number}")
        lines.append(f"    Amount paid: Ksh{booking.amount_paid}")
        lines.append(f"    Transaction code: {booking.transaction_code}")
        lines.append(f"    Transaction date: {booking.transaction_date}")
        lines.append('=' * 65)
        counter += 1 #increment the counter
    
    max_lines_per_page = 25 # reduce the maximum number of lines per page

    page_number = 1
    line_count = 0
    for line in lines:
        if line_count >= max_lines_per_page:
            c.showPage()
            page_number += 1
            line_count = 0
            text_y = letter[1] - top_margin - inch * 1.5 # reset the vertical position of the text on each new page

            #add the logo to each page
            c.drawImage(logo_image, logo_x, logo_y, width=logo_width, height=logo_height)

        c.setFont("Helvetica", 14)
        text_x = inch * 0.5
        c.drawString(text_x, text_y, line)
        text_y -= 0.3 * inch 

        line_count += 1

    c.setFont("Helvetica", 12)
    page_text = f"Page {page_number}"
    c.drawRightString(letter[0] - inch, bottom_margin / 2, page_text)

    c.save()
    buf.seek(0)
    return FileResponse(buf, filename=f'booking_report_{listing.name}.pdf')

@login_required  
@csrf_exempt
def pay_rent(request, pk):
    print("IS THE USER AUTHENTICATED?",request.user.is_authenticated)
    print("REQUEST.USER.IS_TENANT",request.user.is_tenant)

    listing = get_object_or_404(ListingItem, pk=pk)
    if not request.user.is_authenticated or not request.user.is_tenant:
        return HttpResponseForbidden()
    cl = MpesaClient()

    phone_number = request.user.phone_number
    amount = listing.price
    account_reference = 'HouseQuest'
    transaction_desc = 'Payment of rent'
    callback_url = f'https://7964-105-166-142-54.ngrok-free.app/payment/{pk}/mpesa_rent_callback/'
    response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)      
    print("The pay rent view is working")
    print(response)
    return HttpResponse(response)

@csrf_exempt
def mpesa_rent_callback(request, pk):
    listing = get_object_or_404(ListingItem, pk=pk)

    result = request.body
    cl = MpesaClient()
    data = cl.parse_stk_result(result)

    result_code = data['ResultCode']
    result_desc = data['ResultDesc']
    print(data)

    if result_code == 0:
        print("Rent payment was successful")

        amount_paid = data.get('Amount')
        print(f"Rent paid: Ksh{amount_paid}")

        transaction_date_str = str(data.get('TransactionDate'))
        transaction_date = datetime.strptime(transaction_date_str, "%Y%m%d%H%M%S")
        transaction_date = timezone.make_aware(transaction_date) #make the datetime object timezone-aware
        iso_date = transaction_date.isoformat()
        print(f"Transaction date string: {transaction_date}")

        tenant_phone_number =  data.get('PhoneNumber')
        print(f"Tenant's Phone number: {tenant_phone_number}")

        transaction_code = data.get('MpesaReceiptNumber')
        print(f"Transaction code: {transaction_code}")

        listing_name = listing.name
        print("Listing paid for rent: ",listing_name)

        if tenant_phone_number:
            tenant_phone_number = str(tenant_phone_number)
            if tenant_phone_number.startswith('254'):
                tenant_phone_number = '0' + tenant_phone_number[3:]
        
        user = User.objects.filter(phone_number=tenant_phone_number).first()
        if user:
            username = user.get_username()
            print(f"Tenant who paid rent: {username}")
            listing.rented_by.add(user)
            listing.save()
        else:
            print("User not found")

        #creating Renting object
        renting = Renting(
            listing = listing,
            renting_tenant = username,
            transaction_code = transaction_code,

payment/templates/payment/landlord_rent_history.html
{% extends "account/index.html" %}
{% load humanize %}
{% block title %}Landlord Rent History{% endblock %} 

{% block content %}

<div class="flex justify-center items-center mx-8 mt-8 mb-14">
    <div class="p-12 bg-gradient-to-t from-neutral-300 overflow-x-auto">
        <p class="text-center mb-3 text-blue-500 font-bold text-lg underline">Your tenants' rent payment history for <a href="{% url 'listing:view_listing' pk=listing.pk %}" class="hover:text-blue-600">{{ listing_name }} (All time)</a> </p>
        <table class="border border-collapse w-max">
            <thead>
                <tr>
                    <th class="border px-4 py-2"></th>
                    <th class="border px-4 py-2 font-semibold">Tenant name</th>
                    <th class="border px-4 py-2 font-semibold">Tenant No.</th>
                    <th class="border px-4 py-2 font-semibold">Date paid</th>
                    <th class="border px-4 py-2 font-semibold">Rent month</th>
                    <th class="border px-1 py-2 font-semibold">Rent paid (Ksh)</th>
                </tr>
            </thead>
            <tbody>
                {% for renting in rentings %}
                <tr>
                    <td class="border px-4 py-2">{{ forloop.counter }}</td>
                    <td class="border px-4 py-2">{{ renting.renting_tenant }}</td>
                    <td class="border px-4 py-2">{{ renting.tenant_phone_number }}</td>
                    <td class="border px-4 py-2">{{ renting.transaction_date }}</td>                
                    <td class="border px-4 py-2">{{ renting.transaction_date|date:"F" }}</td>
                    <td class="border px-1 py-2">{{ renting.amount_paid|intcomma }}</td>
                </tr>
                {% endfor %}
            </tbody>    
        </table>
        <div class="mt-5 flex flex-col sm:flex-row items-center justify-between">
            <div class="mb-4 sm:mb-0">
                <p class="underline font-bold">Summary</p>
                <p><span class="font-semibold">Total rent paid</span>: Ksh {{ total_rent_paid|intcomma }}</p>
                <p><span class="font-semibold">Average rent paid</span>: Ksh {{ average_rent_paid|intcomma }}</p>
            </div>
            <a href="{% url 'payment:download_rent_history' pk=listing.pk %}" class="bg-blue-500 text-white p-2 rounded"><i class="fas fa-download"></i> Download the summary</a>
        </div>
        
    </div>
</div>
{% endblock %}

payment/templates/payment/landlord_rent_history_pdf.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Rent history</title>
    <style>
        h1{
            text-decoration: underline;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid black;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .number-column {
            width: 30px;
        }
    </style>
</head>
<body>
    <img class="imgLogo" src="{% static 'images/logo.PNG' %}" alt="imgLogo">
    <h1>Your tenants' rent payment history for {{ listing_name }} (All time)</h1>
    <table>
        <thead>
            <tr>
                <th class="number-column">#</th>
                <th>Tenant name</th>
                <th>Tenant No.</th>
                <th>Date paid</th>
                <th>Rent month</th>
                <th>Rent paid (Ksh)</th>
            </tr>
        </thead>
        <tbody>
            {% for renting in rentings %}
            <tr>
                <td class="number-column">{{ forloop.counter }}</td>
                <td>{{ renting.renting_tenant }}</td>
                <td>{{ renting.tenant_phone_number }}</td>
                <td>{{ renting.transaction_date }}</td>                
                <td>{{ renting.transaction_date|date:"F" }}</td>
                <td>{{ renting.amount_paid|intcomma }}</td>
            </tr>
            {% endfor %}
        </tbody>    
    </table>
    <h2>Summary</h2>
    <p>Total rent paid: Ksh {{ total_rent_paid|intcomma }}</p>
    <p>Average rent paid: Ksh {{ average_rent_paid|intcomma }}</p>
</body>
</html>

payment/templates/payment/tenant_rent_history.html
{% extends "account/index.html" %}

{% block title %}Tenant Rent History{% endblock %} 

{% block content %}

<div class="flex justify-center items-center mx-8 mt-8 mb-36">
    <div class="p-12 bg-gradient-to-t from-neutral-300">
        <p class="text-center mb-3 text-blue-500 font-bold text-lg underline">Your rent payment history for <a href="{% url 'listing:view_listing' pk=listing.pk %}" class="hover:text-blue-600">{{ listing_name }}</a> </p>

        <table class="border border-collapse w-max">
            <thead>
                <tr>
                    <th class="border px-4 py-2"></th>
                    <th class="border px-4 py-2 font-semibold">Date paid</th>
                    <th class="border px-4 py-2 font-semibold">Transaction phone no</th>
                    <th class="border px-4 py-2 font-semibold">Rent month</th>
                    <th class="border px-1 py-2 font-semibold">Rent paid (Ksh)</th>
                    <th class="border px-1 py-2 font-semibold">Has moved in</th>
                </tr>
            </thead>
            <tbody>
                {% for renting in rentings %}
                <tr>
                    <td class="border px-4 py-2">{{ forloop.counter }}</td>
                    <td class="border px-4 py-2">{{ renting.transaction_date }}</td>                
                    <td class="border px-4 py-2">{{ renting.tenant_phone_number }}</td>
                    <td class="border px-4 py-2">{{ renting.transaction_date|date:"F" }}</td>
                    <td class="border px-1 py-2">{{ renting.amount_paid }}</td>
                    <td class="border px-1 py-2">
                        {% if renting.listing in rented_listings %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
            
        </table>

    </div>
</div>
{% endblock %}